### ISSUE TITLE
Use card numbers

### ISSUE THREAD

**Issue by amenk** [evasilchenko/trello-postcommit#1]
Trello cards also have numbers. It would be great if a commit like `#1337 Foo bar` could be made. For this there needs to be some project mapping

**Comment by evasilchenko** [comment]
Thanks for the suggestion @amenk I'll take a look at what we can do with this. You're also more than welcome to fork this repo and do a PR :+1:

**Comment by amenk** [comment]
actually I am not sure what happens when moving a card to another board. Maybe it would get a new number.
I started liking the short-link based solution.

I am currently using a Zappier based solution. As soon as I run in the monthly task limit of the free account, I might come back to this.
